<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

<xacro:property name="pi" value="3.1415926535897931" />

  <!-- Inertia parameters -->
    <xacro:property name="base_mass" value="2.0" />  <!-- This mass might be incorrect -->
    <xacro:property name="shoulder_mass" value="7.778" />
    <xacro:property name="upper_arm_mass" value="12.93" />
    <xacro:property name="forearm_mass" value="3.87" />
    <xacro:property name="wrist_1_mass" value="1.96" />
    <xacro:property name="wrist_2_mass" value="1.96" />
    <xacro:property name="wrist_3_mass" value="0.202" />

  <!-- These parameters are borrowed from the urcontrol.conf file
       but are not verified for the correct permutation.
       The permutation was guessed by looking at the UR5 parameters.
       Serious use of these parameters needs further inspection. -->
  <xacro:property name="shoulder_cog" value="0.00008 0.00244 -0.037" />
  <xacro:property name="upper_arm_cog" value="0.00001 0.15061 0.38757" />
  <xacro:property name="forearm_cog" value="-0.00012 0.06112 0.1984" />
  <xacro:property name="wrist_1_cog" value="-0.00021 -0.00112 0.02269" />
  <xacro:property name="wrist_2_cog" value="-0.00021 0.00112 0.002269" />
  <xacro:property name="wrist_3_cog" value="0 -0.001156 -0.00149" />

  <!-- Kinematic model -->
  <!-- Properties from urcontrol.conf -->
  <xacro:property name="ur10_d1" value="0.1273" />
  <xacro:property name="ur10_a2" value="-0.612" />
  <xacro:property name="ur10_a3" value="-0.5723" />
  <xacro:property name="ur10_d4" value="0.163941" />
  <xacro:property name="ur10_d5" value="0.1157" />
  <xacro:property name="ur10_d6" value="0.0922" />

  <!-- Arbitrary offsets for shoulder/elbow joints -->
  <xacro:property name="shoulder_offset" value="0.220941" />  <!-- measured from model -->
  <xacro:property name="elbow_offset" value="-0.1719" /> <!-- measured from model -->

  <!-- link lengths used in model -->
  <xacro:property name="shoulder_height" value="${ur10_d1}" />
  <xacro:property name="upper_arm_length" value="${-ur10_a2}" />
  <xacro:property name="forearm_length" value="${-ur10_a3}" />
  <xacro:property name="wrist_1_length" value="${ur10_d4 - elbow_offset - shoulder_offset}" />
  <xacro:property name="wrist_2_length" value="${ur10_d5}" />
  <xacro:property name="wrist_3_length" value="${ur10_d6}" />

  <xacro:macro name="cylinder_inertial" params="radius length mass *origin">
    <inertial>
      <mass value="${mass}" />
      <xacro:insert_block name="origin" />
      <inertia ixx="${0.0833333 * mass * (3 * radius * radius + length * length)}" ixy="0.0" ixz="0.0"
        iyy="${0.0833333 * mass * (3 * radius * radius + length * length)}" iyz="0.0"
        izz="${0.5 * mass * radius * radius}" />
    </inertial>
  </xacro:macro>


  <xacro:macro name="ur10_robot" params="parent prefix joint_limited
     shoulder_pan_lower_limit:=${-pi}    shoulder_pan_upper_limit:=${pi}
     shoulder_lift_lower_limit:=${-pi}    shoulder_lift_upper_limit:=${pi}
     elbow_joint_lower_limit:=${-pi}    elbow_joint_upper_limit:=${pi}
     wrist_1_lower_limit:=${-pi}    wrist_1_upper_limit:=${pi}
     wrist_2_lower_limit:=${-pi}    wrist_2_upper_limit:=${pi}
     wrist_3_lower_limit:=${-pi}    wrist_3_upper_limit:=${pi}">


    <joint name="cabinet_u10_joint" type="fixed">
      <parent link="${parent}" />
      <child link = "ur10_base_link" />
      <origin xyz="0.133 0.0 0.416" rpy="0.0 0.0 0.0" />
    </joint>

    <link name="ur10_base_link" >
      <visual>
        <geometry>
          <mesh filename="package://neo_simulation/robots/mmo_700/meshes/base.dae"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://neo_simulation/robots/mmo_700/meshes/base.dae"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.038" mass="${base_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="shoulder_pan_joint" type="revolute">
      <parent link="ur10_base_link" />
      <child link = "shoulder_link" />
      <origin xyz="0.0 0.0 ${shoulder_height}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 0 1" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="330.0" velocity="2.16"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${shoulder_pan_lower_limit}" upper="${shoulder_pan_upper_limit}" effort="330.0" velocity="2.16"/>
      </xacro:if>
      <dynamics damping="0.5" friction="10.0"/>
    </joint>

    <link name="shoulder_link">
      <visual>
        <geometry>
          <mesh filename="package://neo_simulation/robots/mmo_700/meshes/shoulder.dae"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://neo_simulation/robots/mmo_700/meshes/shoulder.dae"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.178" mass="${shoulder_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="shoulder_lift_joint" type="revolute">
      <parent link="shoulder_link" />
      <child link = "upper_arm_link" />
      <origin xyz="0.0 ${shoulder_offset} 0.0" rpy="0.0 -1.25 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="330.0" velocity="2.16"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${shoulder_lift_lower_limit}" upper="${shoulder_lift_upper_limit}" effort="330.0" velocity="2.16"/>
      </xacro:if>
      <dynamics damping="0.5" friction="10.0"/>
    </joint>

    <link name="upper_arm_link">
      <visual>
        <geometry>
          <mesh filename="package://neo_simulation/robots/mmo_700/meshes/upperarm.dae"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://neo_simulation/robots/mmo_700/meshes/upperarm.dae"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="${-ur10_a2}" mass="${upper_arm_mass}">
        <origin xyz="0.0 0.0 ${-ur10_a2/2.0}" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="elbow_joint" type="revolute">
      <parent link="upper_arm_link" />
      <child link = "forearm_link" />
      <origin xyz="0.0 ${elbow_offset} ${upper_arm_length}" rpy="0.0 -1.95 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-pi}" upper="${pi}" effort="150.0" velocity="3.15"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${elbow_joint_lower_limit}" upper="${elbow_joint_upper_limit}" effort="150.0" velocity="3.15"/>
      </xacro:if>
      <dynamics damping="0.5" friction="10.0"/>
    </joint>

    <link name="forearm_link">
      <visual>
         <geometry>
          <mesh filename="package://neo_simulation/robots/mmo_700/meshes/forearm.dae"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://neo_simulation/robots/mmo_700/meshes/forearm.dae"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="${-ur10_a3}" mass="${forearm_mass}">
        <origin xyz="0.0 0.0 ${-ur10_a3/2.0}" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="wrist_1_joint" type="revolute">
      <parent link="forearm_link" />
      <child link = "wrist_1_link" />
      <origin xyz="0.0 0.0 ${forearm_length}" rpy="0.0 ${pi / 2.0} 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${wrist_1_lower_limit}" upper="${wrist_1_upper_limit}" effort="54.0" velocity="3.2"/>
      </xacro:if>
      <dynamics damping="0.5" friction="10.0"/>
    </joint>

    <link name="wrist_1_link">
      <visual>
        <geometry>
          <mesh filename="package://neo_simulation/robots/mmo_700/meshes/wrist1.dae"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://neo_simulation/robots/mmo_700/meshes/wrist1.dae"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.12" mass="${wrist_1_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="wrist_2_joint" type="revolute">
      <parent link="wrist_1_link" />
      <child link = "wrist_2_link" />
      <origin xyz="0.0 ${wrist_1_length} 0.0" rpy="0.0 0.0 0.0" />
      <axis xyz="0 0 1" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${wrist_2_lower_limit}" upper="${wrist_2_upper_limit}" effort="54.0" velocity="3.2"/>
      </xacro:if>
      <dynamics damping="0.5" friction="10.0"/>
    </joint>

    <link name="wrist_2_link">
      <visual>
        <geometry>
          <mesh filename="package://neo_simulation/robots/mmo_700/meshes/wrist2.dae"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://neo_simulation/robots/mmo_700/meshes/wrist2.dae"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.12" mass="${wrist_2_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="wrist_3_joint" type="revolute">
      <parent link="wrist_2_link" />
      <child link = "wrist_3_link" />
      <origin xyz="0.0 0.0 ${wrist_2_length}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${wrist_3_lower_limit}" upper="${wrist_3_upper_limit}" effort="54.0" velocity="3.2"/>
      </xacro:if>
      <dynamics damping="0.5" friction="10.0"/>
    </joint>

    <link name="wrist_3_link">
      <visual>
        <geometry>
          <mesh filename="package://neo_simulation/robots/mmo_700/meshes/wrist3.dae"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://neo_simulation/robots/mmo_700/meshes/wrist3.dae"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.12" mass="${wrist_3_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="ee_fixed_joint" type="fixed">
      <parent link="wrist_3_link" />
      <child link = "ee_link" />
      <origin xyz="0.0 ${wrist_3_length} 0.0" rpy="0.0 0.0 ${pi/2.0}" />
    </joint>

    <link name="ee_link">
      <collision>
        <geometry>
          <box size="0.01 0.01 0.01"/>
        </geometry>
        <origin rpy="0 0 0" xyz="-0.01 0 0"/>
      </collision>
</link>

  <transmission name="shoulder_pan_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="shoulder_pan_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="shoulder_pan_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="shoulder_lift_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="shoulder_lift_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="shoulder_lift_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="elbow_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="elbow_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="elbow_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="wrist_1_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="wrist_1_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="wrist_1_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="wrist_2_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="wrist_2_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="wrist_2_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="wrist_3_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="wrist_3_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="wrist_3_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <!-- nothing to do here at the moment -->
  <!-- ROS ur10_base_link to UR 'Base' Coordinates transform -->
  <link name="base"/>
  <joint name="ur10_base_link-base_fixed_joint" type="fixed">
    <!-- NOTE: this rotation is only needed as long as ur10_base_link itself is
                 not corrected wrt the real robot (ie: rotated over 180
                 degrees)
      -->
    <origin rpy="0 0 -3.14159265359" xyz="0 0 0"/>
    <parent link="ur10_base_link"/>
    <child link="base"/>
  </joint>
  <!-- Frame coincident with all-zeros TCP on UR controller -->
  <link name="tool0"/>
  <joint name="wrist_3_link-tool0_fixed_joint" type="fixed">
    <origin rpy="-1.57079632679 0 0" xyz="0 0.0922 0"/>
    <parent link="wrist_3_link"/>
    <child link="tool0"/>
  </joint>

  <link name="H1_base_attach"/>
  <material name="Blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>
  <material name="Green">
    <color rgba="0.0 0.8 0.0 1.0"/>
  </material>
  <material name="BiotacGreen">
    <color rgba="0.31 0.85 0.42 1.0"/>
  </material>
  <material name="Grey">
    <color rgba="0.2 0.2 0.2 1.0"/>
  </material>
  <material name="LightGrey">
    <color rgba="0.6 0.6 0.6 1.0"/>
  </material>
  <material name="Red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>
  <material name="White">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>
  <link name="H1_ur10_base_link">
    <inertial>
      <origin rpy="0 0 0" xyz="-8.6116E-06 -0.0058125 0.028294"/>
      <mass value="0.07527"/>
      <inertia ixx="0.00014442" ixy="1.2033E-08" ixz="-5.9646E-10" iyy="0.00014979" iyz="-1.0288E-05" izz="5.2943E-05"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://neo_simulation/robots/mmo_700/meshes/palm_link_simple.dae"/>
      </geometry>
      <material name="light_grey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://neo_simulation/robots/mmo_700/meshes/palm_link_simple.dae"/>
      </geometry>
      <material name="light_grey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </collision>
  </link>
  <joint name="H1Base" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="H1_base_attach"/>
    <child link="H1_wrist_attach"/>
  </joint>
  
  <link name="H1_insert_F1"/>
  <joint name="H1_dummy_joint_1" type="fixed">
    <origin rpy="0 0 2.3562" xyz="-0.045 -0.025981 0"/>
    <axis xyz="0 -1 0"/>
    <parent link="H1_ur10_base_link"/>
    <child link="H1_insert_F1"/>
  </joint>
  <link name="H1_insert_F2"/>
  <joint name="H1_dummy_joint_2" type="fixed">
    <origin rpy="0 0 0" xyz="0 0.029019 0"/>
    <axis xyz="0 -1 0"/>
    <parent link="H1_ur10_base_link"/>
    <child link="H1_insert_F2"/>
  </joint>
  <link name="H1_insert_F3"/>
  <joint name="H1_dummy_joint_3" type="fixed">
    <origin rpy="0 0 -2.3562" xyz="0.045 -0.025981 0"/>
    <axis xyz="0 -1 0"/>
    <parent link="H1_ur10_base_link"/>
    <child link="H1_insert_F3"/>
  </joint>
  <link name="H1_wrist_attach"/>
  <joint name="H1_ur10_base_link_wrist_attach" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 -0.0005"/>
    <child link="H1_ur10_base_link"/>
    <parent link="H1_wrist_attach"/>
  </joint>
  <link name="H1_F1_palm_link">
    <inertial>
      <origin rpy="0 0 0" xyz="-0.00681802120880393 -0.00947020456878004 0.067587996682422"/>
      <mass value="0.0341482312344481"/>
      <inertia ixx="2.79747833772125E-05" ixy="-5.50900644725373E-08" ixz="-2.82072424927723E-07" iyy="2.67800858812928E-05" iyz="3.1953125069394E-06" izz="9.86122271726361E-06"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://neo_simulation/robots/mmo_700/meshes/finger_palm_link.dae"/>
      </geometry>
      <material name="light_grey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </visual>
    <!-- Collision mesh no needed as it is part of palm_link_simple.dae collision mesh -->
    <!--xacro:mesh_collision file_name="finger_palm_link.dae">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <xacro:light_grey/>
      </xacro:mesh_collision-->
  </link>
  <link name="H1_F1_ur10_base_link">
    <inertial>
      <origin rpy="0 0 0" xyz="-0.000142856770000038 0.0265691681336443 0.0538751581621436"/>
      <mass value="0.174652229503358"/>
      <inertia ixx="0.000298372741514267" ixy="-5.05751882577435E-07" ixz="1.94982779411417E-07" iyy="0.000299629589232877" iyz="2.79565205733806E-05" izz="0.000134889645145365"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://neo_simulation/robots/mmo_700/meshes/finger_base_link_simple.dae"/>
      </geometry>
      <material name="light_grey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://neo_simulation/robots/mmo_700/meshes/finger_base_link_simple.dae"/>
      </geometry>
      <material name="light_grey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </collision>
  </link>
  <link name="H1_F1_link_1">
    <inertial>
      <origin rpy="0 0 0" xyz="-0.000141876508729455 -0.00135409566494088 0.0277606215980989"/>
      <mass value="0.0827759744227546"/>
      <inertia ixx="4.61070151157777E-05" ixy="7.47741111557837E-08" ixz="-2.25165057702697E-07" iyy="5.27678327317508E-05" iyz="-3.64603343546298E-07" izz="2.89599551320955E-05"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://neo_simulation/robots/mmo_700/meshes/finger_prox_link_simple.dae"/>
      </geometry>
      <material name="light_grey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://neo_simulation/robots/mmo_700/meshes/finger_prox_link_simple.dae"/>
      </geometry>
      <material name="light_grey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </collision>
  </link>
  <link name="H1_F1_link_2">
    <inertial>
      <origin rpy="0 0 0" xyz="0.000506812071918918 -0.00091292934992606 0.0156620851768385"/>
      <mass value="0.0270049614151599"/>
      <inertia ixx="1.06942730265546E-05" ixy="-7.1810089794211E-09" ixz="-3.49957211410822E-07" iyy="1.05772889540593E-05" iyz="-8.38595987731518E-07" izz="3.27173446995846E-06"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://neo_simulation/robots/mmo_700/meshes/finger_dist_link_simple.dae"/>
      </geometry>
      <material name="light_grey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://neo_simulation/robots/mmo_700/meshes/finger_dist_link_simple.dae"/>
      </geometry>
      <material name="light_grey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </collision>
  </link>
  <joint name="H1_F1Palm" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="H1_insert_F1"/>
    <child link="H1_F1_palm_link"/>
  </joint>
  <joint name="H1_F1J1" type="fixed">
    <origin rpy="-8.8818E-16 -1.0061E-16 0.022402" xyz="0 0 0.00016528"/>
    <axis xyz="0 0 1"/>
    <parent link="H1_F1_palm_link"/>
    <child link="H1_F1_ur10_base_link"/>
    <limit effort="50" lower="-0.785398163397" upper="0.785398163397" velocity="1.0"/>
    <dynamics damping="0.0" friction="10.0"/>
  </joint>
  <joint name="H1_F1J2" type="fixed">
    <origin rpy="0.070695 6.9389E-16 2.0947E-16" xyz="0 0.035 0.11683"/>
    <axis xyz="1 0 0"/>
    <parent link="H1_F1_ur10_base_link"/>
    <child link="H1_F1_link_1"/>
    <limit effort="50" lower="-1.3962634016" upper="1.0471975512" velocity="1.0"/>
    <dynamics damping="0.0" friction="10.0"/>
  </joint>
  <joint name="H1_F1J3" type="revolute">
    <origin rpy="-0.0068649 1.7347E-18 1.6176E-16" xyz="0 0 0.06"/>
    <axis xyz="1 0 0"/>
    <parent link="H1_F1_link_1"/>
    <child link="H1_F1_link_2"/>
    <limit effort="50" lower="-1.0471975512" upper="1.57079632679" velocity="1.0"/>
    <dynamics damping="0.0" friction="10.0"/>
  </joint>

  <transmission name="H1_F1J3_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="H1_F1J3">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="H1_F1J3">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
  </transmission>
  <!-- finger tip -->
  <link name="H1_F1_tip">
    <inertial>
      <origin rpy="0 0 0" xyz="-0.000925580990320645 -0.00495543398528436 0.0355865585792753"/>
      <mass value="0.00906322686585137"/>
      <inertia ixx="1.10049088227995E-06" ixy="-3.7290982171096E-09" ixz="-9.54389365908683E-09" iyy="1.36130530510584E-06" iyz="6.66133713720777E-08" izz="6.42259773618367E-07"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://neo_simulation/robots/mmo_700/meshes/omd-d18-tip.dae"/>
      </geometry>
      <material name="light_grey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://neo_simulation/robots/mmo_700/meshes/omd-d18-tip.dae"/>
      </geometry>
      <material name="light_grey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </collision>
  </link>
  <link name="H1_F1_optoforce"/>
  <joint name="H1_F1_tip_to_optoforce" type="fixed">
    <parent link="H1_F1_tip"/>
    <child link="H1_F1_optoforce"/>
    <origin rpy="-0.35 0 0" xyz="0 -0.006 0.046"/>
  </joint>
  <joint name="H1_F1_tip" type="fixed">
    <parent link="H1_F1_link_2"/>
    <child link="H1_F1_tip"/>
  </joint>
  <link name="H1_F2_palm_link">
    <inertial>
      <origin rpy="0 0 0" xyz="-0.00681802120880393 -0.00947020456878004 0.067587996682422"/>
      <mass value="0.0341482312344481"/>
      <inertia ixx="2.79747833772125E-05" ixy="-5.50900644725373E-08" ixz="-2.82072424927723E-07" iyy="2.67800858812928E-05" iyz="3.1953125069394E-06" izz="9.86122271726361E-06"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://neo_simulation/robots/mmo_700/meshes/finger_palm_link.dae"/>
      </geometry>
      <material name="light_grey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </visual>
    <!-- Collision mesh no needed as it is part of palm_link_simple.dae collision mesh -->
    <!--xacro:mesh_collision file_name="finger_palm_link.dae">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <xacro:light_grey/>
      </xacro:mesh_collision-->
  </link>
  <link name="H1_F2_ur10_base_link">
    <inertial>
      <origin rpy="0 0 0" xyz="-0.000142856770000038 0.0265691681336443 0.0538751581621436"/>
      <mass value="0.174652229503358"/>
      <inertia ixx="0.000298372741514267" ixy="-5.05751882577435E-07" ixz="1.94982779411417E-07" iyy="0.000299629589232877" iyz="2.79565205733806E-05" izz="0.000134889645145365"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://neo_simulation/robots/mmo_700/meshes/finger_base_link_simple.dae"/>
      </geometry>
      <material name="light_grey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://neo_simulation/robots/mmo_700/meshes/finger_base_link_simple.dae"/>
      </geometry>
      <material name="light_grey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </collision>
  </link>
  <link name="H1_F2_link_1">
    <inertial>
      <origin rpy="0 0 0" xyz="-0.000141876508729455 -0.00135409566494088 0.0277606215980989"/>
      <mass value="0.0827759744227546"/>
      <inertia ixx="4.61070151157777E-05" ixy="7.47741111557837E-08" ixz="-2.25165057702697E-07" iyy="5.27678327317508E-05" iyz="-3.64603343546298E-07" izz="2.89599551320955E-05"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://neo_simulation/robots/mmo_700/meshes/finger_prox_link_simple.dae"/>
      </geometry>
      <material name="light_grey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://neo_simulation/robots/mmo_700/meshes/finger_prox_link_simple.dae"/>
      </geometry>
      <material name="light_grey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </collision>
  </link>
  <link name="H1_F2_link_2">
    <inertial>
      <origin rpy="0 0 0" xyz="0.000506812071918918 -0.00091292934992606 0.0156620851768385"/>
      <mass value="0.0270049614151599"/>
      <inertia ixx="1.06942730265546E-05" ixy="-7.1810089794211E-09" ixz="-3.49957211410822E-07" iyy="1.05772889540593E-05" iyz="-8.38595987731518E-07" izz="3.27173446995846E-06"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://neo_simulation/robots/mmo_700/meshes/finger_dist_link_simple.dae"/>
      </geometry>
      <material name="light_grey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://neo_simulation/robots/mmo_700/meshes/finger_dist_link_simple.dae"/>
      </geometry>
      <material name="light_grey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </collision>
  </link>
  <joint name="H1_F2Palm" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="H1_insert_F2"/>
    <child link="H1_F2_palm_link"/>
  </joint>
  <joint name="H1_F2J1" type="fixed">
    <origin rpy="-8.8818E-16 -1.0061E-16 0.022402" xyz="0 0 0.00016528"/>
    <axis xyz="0 0 1"/>
    <parent link="H1_F2_palm_link"/>
    <child link="H1_F2_ur10_base_link"/>
    <limit effort="30" lower="-0.785398163397" upper="0.785398163397" velocity="1.0"/>
    <dynamics damping="0.0" friction="10.0"/>
  </joint>
  <joint name="H1_F2J2" type="fixed">
    <origin rpy="0.070695 6.9389E-16 2.0947E-16" xyz="0 0.035 0.11683"/>
    <axis xyz="1 0 0"/>
    <parent link="H1_F2_ur10_base_link"/>
    <child link="H1_F2_link_1"/>
    <limit effort="30" lower="-1.3962634016" upper="1.0471975512" velocity="1.0"/>
    <dynamics damping="0.0" friction="10.0"/>
  </joint>
  <joint name="H1_F2J3" type="revolute">
    <origin rpy="-0.0068649 1.7347E-18 1.6176E-16" xyz="0 0 0.06"/>
    <axis xyz="1 0 0"/>
    <parent link="H1_F2_link_1"/>
    <child link="H1_F2_link_2"/>
    <limit effort="30" lower="-1.0471975512" upper="1.57079632679" velocity="1.0"/>
    <dynamics damping="0.0" friction="10.0"/>
  </joint>
  <transmission name="H1_F2J3_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="H1_F2J3">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="H1_F2J3">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
  </transmission>
  <!-- finger tip -->
  <link name="H1_F2_tip">
    <inertial>
      <origin rpy="0 0 0" xyz="-0.000925580990320645 -0.00495543398528436 0.0355865585792753"/>
      <mass value="0.00906322686585137"/>
      <inertia ixx="1.10049088227995E-06" ixy="-3.7290982171096E-09" ixz="-9.54389365908683E-09" iyy="1.36130530510584E-06" iyz="6.66133713720777E-08" izz="6.42259773618367E-07"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://neo_simulation/robots/mmo_700/meshes/omd-d18-tip.dae"/>
      </geometry>
      <material name="light_grey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://neo_simulation/robots/mmo_700/meshes/omd-d18-tip.dae"/>
      </geometry>
      <material name="light_grey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </collision>
  </link>
  <link name="H1_F2_optoforce"/>
  <joint name="H1_F2_tip_to_optoforce" type="fixed">
    <parent link="H1_F2_tip"/>
    <child link="H1_F2_optoforce"/>
    <origin rpy="-0.35 0 0" xyz="0 -0.006 0.046"/>
  </joint>
  <joint name="H1_F2_tip" type="fixed">
    <parent link="H1_F2_link_2"/>
    <child link="H1_F2_tip"/>
  </joint>
  <link name="H1_F3_palm_link">
    <inertial>
      <origin rpy="0 0 0" xyz="-0.00681802120880393 -0.00947020456878004 0.067587996682422"/>
      <mass value="0.0341482312344481"/>
      <inertia ixx="2.79747833772125E-05" ixy="-5.50900644725373E-08" ixz="-2.82072424927723E-07" iyy="2.67800858812928E-05" iyz="3.1953125069394E-06" izz="9.86122271726361E-06"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://neo_simulation/robots/mmo_700/meshes/finger_palm_link.dae"/>
      </geometry>
      <material name="light_grey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </visual>
    <!-- Collision mesh no needed as it is part of palm_link_simple.dae collision mesh -->
    <!--xacro:mesh_collision file_name="finger_palm_link.dae">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <xacro:light_grey/>
      </xacro:mesh_collision-->
  </link>
  <link name="H1_F3_ur10_base_link">
    <inertial>
      <origin rpy="0 0 0" xyz="-0.000142856770000038 0.0265691681336443 0.0538751581621436"/>
      <mass value="0.174652229503358"/>
      <inertia ixx="0.000298372741514267" ixy="-5.05751882577435E-07" ixz="1.94982779411417E-07" iyy="0.000299629589232877" iyz="2.79565205733806E-05" izz="0.000134889645145365"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://neo_simulation/robots/mmo_700/meshes/finger_base_link_simple.dae"/>
      </geometry>
      <material name="light_grey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://neo_simulation/robots/mmo_700/meshes/finger_base_link_simple.dae"/>
      </geometry>
      <material name="light_grey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </collision>
  </link>
  <link name="H1_F3_link_1">
    <inertial>
      <origin rpy="0 0 0" xyz="-0.000141876508729455 -0.00135409566494088 0.0277606215980989"/>
      <mass value="0.0827759744227546"/>
      <inertia ixx="4.61070151157777E-05" ixy="7.47741111557837E-08" ixz="-2.25165057702697E-07" iyy="5.27678327317508E-05" iyz="-3.64603343546298E-07" izz="2.89599551320955E-05"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://neo_simulation/robots/mmo_700/meshes/finger_prox_link_simple.dae"/>
      </geometry>
      <material name="light_grey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://neo_simulation/robots/mmo_700/meshes/finger_prox_link_simple.dae"/>
      </geometry>
      <material name="light_grey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </collision>
  </link>
  <link name="H1_F3_link_2">
    <inertial>
      <origin rpy="0 0 0" xyz="0.000506812071918918 -0.00091292934992606 0.0156620851768385"/>
      <mass value="0.0270049614151599"/>
      <inertia ixx="1.06942730265546E-05" ixy="-7.1810089794211E-09" ixz="-3.49957211410822E-07" iyy="1.05772889540593E-05" iyz="-8.38595987731518E-07" izz="3.27173446995846E-06"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://neo_simulation/robots/mmo_700/meshes/finger_dist_link_simple.dae"/>
      </geometry>
      <material name="light_grey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://neo_simulation/robots/mmo_700/meshes/finger_dist_link_simple.dae"/>
      </geometry>
      <material name="light_grey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </collision>
  </link>
  <joint name="H1_F3Palm" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="H1_insert_F3"/>
    <child link="H1_F3_palm_link"/>
  </joint>
  <joint name="H1_F3J1" type="fixed">
    <origin rpy="-8.8818E-16 -1.0061E-16 0.022402" xyz="0 0 0.00016528"/>
    <axis xyz="0 0 1"/>
    <parent link="H1_F3_palm_link"/>
    <child link="H1_F3_ur10_base_link"/>
    <limit effort="30" lower="-0.785398163397" upper="0.785398163397" velocity="1.0"/>
    <dynamics damping="0.0" friction="10.0"/>
  </joint>
  <joint name="H1_F3J2" type="fixed">
    <origin rpy="0.070695 6.9389E-16 2.0947E-16" xyz="0 0.035 0.11683"/>
    <axis xyz="1 0 0"/>
    <parent link="H1_F3_ur10_base_link"/>
    <child link="H1_F3_link_1"/>
    <limit effort="30" lower="-1.3962634016" upper="1.0471975512" velocity="1.0"/>
    <dynamics damping="0.0" friction="10.0"/>
  </joint>
  <joint name="H1_F3J3" type="revolute">
    <origin rpy="-0.0068649 1.7347E-18 1.6176E-16" xyz="0 0 0.06"/>
    <axis xyz="1 0 0"/>
    <parent link="H1_F3_link_1"/>
    <child link="H1_F3_link_2"/>
    <limit effort="30" lower="-1.0471975512" upper="1.57079632679" velocity="1.0"/>
    <dynamics damping="0.0" friction="10.0"/>
  </joint>
  <transmission name="H1_F3J3_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="H1_F3J3">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="H1_F3J3">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
  </transmission>
  <!-- finger tip -->
  <link name="H1_F3_tip">
    <inertial>
      <origin rpy="0 0 0" xyz="-0.000925580990320645 -0.00495543398528436 0.0355865585792753"/>
      <mass value="0.00906322686585137"/>
      <inertia ixx="1.10049088227995E-06" ixy="-3.7290982171096E-09" ixz="-9.54389365908683E-09" iyy="1.36130530510584E-06" iyz="6.66133713720777E-08" izz="6.42259773618367E-07"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://neo_simulation/robots/mmo_700/meshes/omd-d18-tip.dae"/>
      </geometry>
      <material name="light_grey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://neo_simulation/robots/mmo_700/meshes/omd-d18-tip.dae"/>
      </geometry>
      <material name="light_grey">
        <color rgba="0.75 0.75 0.75 1.0"/>
      </material>
    </collision>
  </link>
  <link name="H1_F3_optoforce"/>
  <joint name="H1_F3_tip_to_optoforce" type="fixed">
    <parent link="H1_F3_tip"/>
    <child link="H1_F3_optoforce"/>
    <origin rpy="-0.35 0 0" xyz="0 -0.006 0.046"/>
  </joint>
  <joint name="H1_F3_tip" type="fixed">
    <parent link="H1_F3_link_2"/>
    <child link="H1_F3_tip"/>
  </joint>
  
  
  <joint name="arm_to_hand" type="fixed">
    <parent link="ee_link"/>
    <child link="H1_base_attach"/>
    <origin rpy="1.57079632679 3.14159265359 1.57079632679" xyz="0.012 0.0 0.0"/>
  </joint>
  
  
  <gazebo reference="H1_F1J1">
    <implicitSpringDamper>1</implicitSpringDamper>
  </gazebo>
  <gazebo reference="H1_F1J2">
    <implicitSpringDamper>1</implicitSpringDamper>
  </gazebo>
  <gazebo reference="H1_F1J3">
    <implicitSpringDamper>1</implicitSpringDamper>
  </gazebo>
  <gazebo reference="H1_F2J1">
    <implicitSpringDamper>1</implicitSpringDamper>
  </gazebo>
  <gazebo reference="H1_F2J2">
    <implicitSpringDamper>1</implicitSpringDamper>
  </gazebo>
  <gazebo reference="H1_F2J3">
    <implicitSpringDamper>1</implicitSpringDamper>
  </gazebo>
  <gazebo reference="H1_F3J1">
    <implicitSpringDamper>1</implicitSpringDamper>
  </gazebo>
  <gazebo reference="H1_F3J2">
    <implicitSpringDamper>1</implicitSpringDamper>
  </gazebo>
  <gazebo reference="H1_F3J3">
    <implicitSpringDamper>1</implicitSpringDamper>
  </gazebo>
  
  <gazebo reference="H1_F1_link_1">  
    <kp>1000000.0</kp>
    <kd>100.0</kd>
    <mu1>100000</mu1>
    <mu2>100000</mu2>
    <fdir1>1 0 0</fdir1>
    <maxVel>1.0</maxVel>
    <minDepth>0.001</minDepth>
    
    <material>Gazebo/DarkGrey</material>
  </gazebo>
  <gazebo reference="H1_F1_link_2">
    <kp>1000000.0</kp>
    <kd>100.0</kd>
    <mu1>100000</mu1>
    <mu2>100000</mu2>
    <fdir1>1 0 0</fdir1>
    <maxVel>1.0</maxVel>
    <minDepth>0.001</minDepth>
    
    <material>Gazebo/DarkGrey</material>
  </gazebo><gazebo reference="H1_F1_tip">
    <kp>1000000.0</kp>
    <kd>10.0</kd>
    <mu1>100000</mu1>
    <mu2>100000</mu2>
    <fdir1>1 0 0</fdir1>
    <maxVel>1.0</maxVel>
    <minDepth>0.001</minDepth>
    
    <material>Gazebo/DarkGrey</material>
  </gazebo>
  
  <gazebo reference="H1_F2_link_1">
    <kp>1000000.0</kp>
    <kd>10.0</kd>
    <mu1>100000</mu1>
    <mu2>100000</mu2>
    <fdir1>1 0 0</fdir1>
    <maxVel>1.0</maxVel>
    <minDepth>0.001</minDepth>
    
    <material>Gazebo/DarkGrey</material>
  </gazebo>
  <gazebo reference="H1_F2_link_2">
    <kp>1000000.0</kp>
    <kd>10.0</kd>
    <mu1>100000</mu1>
    <mu2>100000</mu2>
    <fdir1>1 0 0</fdir1>
    <maxVel>1.0</maxVel>
    <minDepth>0.001</minDepth>
    
    <material>Gazebo/DarkGrey</material>
  </gazebo><gazebo reference="H1_F2_tip">
    <kp>1000000.0</kp>
    <kd>10.0</kd>
    <mu1>100000</mu1>
    <mu2>100000</mu2>
    <fdir1>1 0 0</fdir1>
    <maxVel>1.0</maxVel>
    <minDepth>0.001</minDepth>
    
    <material>Gazebo/DarkGrey</material>
  </gazebo>
  
  <gazebo reference="H1_F3_link_1">
    <kp>1000000.0</kp>
    <kd>10.0</kd>
    <mu1>100000</mu1>
    <mu2>100000</mu2>
    <fdir1>1 0 0</fdir1>
    <maxVel>1.0</maxVel>
    <minDepth>0.001</minDepth>
    
    <material>Gazebo/DarkGrey</material>
  </gazebo>
  <gazebo reference="H1_F3_link_2">
    <kp>1000000.0</kp>
    <kd>10.0</kd>
    <mu1>100000</mu1>
    <mu2>100000</mu2>
    <fdir1>1 0 0</fdir1>
    <maxVel>1.0</maxVel>
    <minDepth>0.001</minDepth>
    
    <material>Gazebo/DarkGrey</material>
  </gazebo><gazebo reference="H1_F3_tip">
    <kp>1000000.0</kp>
    <kd>10.0</kd>
    <mu1>100000</mu1>
    <mu2>100000</mu2>
    <fdir1>1 0 0</fdir1>
    <maxVel>1.0</maxVel>
    <minDepth>0.001</minDepth>
    
    <material>Gazebo/DarkGrey</material>
  </gazebo>
  
  <gazebo reference="H1_F1_ur10_base_link">
    <kp>1000000.0</kp>
    <kd>10.0</kd>
    <mu1>1000</mu1>
    <mu2>1000</mu2>
    <fdir1>1 0 0</fdir1>
    <maxVel>1.0</maxVel>
    <minDepth>0.001</minDepth>
    
    <material>Gazebo/DarkGrey</material>
  </gazebo>
  <gazebo reference="H1_F2_ur10_base_link">
    <kp>1000000.0</kp>
    <kd>10.0</kd>
    <mu1>100000</mu1>
    <mu2>100000</mu2>
    <fdir1>1 0 0</fdir1>
    <maxVel>1.0</maxVel>
    <minDepth>0.001</minDepth>
    
    <material>Gazebo/DarkGrey</material>
  </gazebo>
  <gazebo reference="H1_F3_ur10_base_link">
    <kp>1000000.0</kp>
    <kd>10.0</kd>
    <mu1>100000</mu1>
    <mu2>100000</mu2>
    <fdir1>1 0 0</fdir1>
    <maxVel>1.0</maxVel>
    <minDepth>0.001</minDepth>
    
    <material>Gazebo/DarkGrey</material>
  </gazebo>
  
  <gazebo reference="H1_F1_palm_link">
    <kp>1000000.0</kp>
    <kd>10.0</kd>
    <mu1>100000</mu1>
    <mu2>100000</mu2>
    <fdir1>1 0 0</fdir1>
    <maxVel>1.0</maxVel>
    <minDepth>0.001</minDepth>
    
    <material>Gazebo/DarkGrey</material>
  </gazebo>
  <gazebo reference="H1_F2_palm_link">
    <kp>1000000.0</kp>
    <kd>10.0</kd>
    <mu1>100000</mu1>
    <mu2>100000</mu2>
    <fdir1>1 0 0</fdir1>
    <maxVel>1.0</maxVel>
    <minDepth>0.001</minDepth>
    
    <material>Gazebo/DarkGrey</material>
  </gazebo>
  <gazebo reference="H1_F3_palm_link">
    <kp>1000000.0</kp>
    <kd>10.0</kd>
    <mu1>100000</mu1>
    <mu2>100000</mu2>
    <fdir1>1 0 0</fdir1>
    <maxVel>1.0</maxVel>
    <minDepth>0.001</minDepth>
    
    <material>Gazebo/DarkGrey</material>
  </gazebo>
  
  <gazebo reference="H1_ur10_base_link">
    <kp>1000000.0</kp>
    <kd>10.0</kd>
    <mu1>100000</mu1>
    <mu2>100000</mu2>
    <fdir1>1 0 0</fdir1>
    <maxVel>1.0</maxVel>
    <minDepth>0.001</minDepth>
    
    <material>Gazebo/DarkGrey</material>
  </gazebo>
  </xacro:macro>
</robot>
